# This workflow will build a Java project with Gradle  
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: ELT Snapshot Build

on:
  push:
    branches: 
      - 'master'
  pull_request:
    branches: 
      - 'master'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone ELTCore repository
      uses: actions/checkout@v2
      with:
        repository: MoegTech/ELTCore
        ref: master
        path: EltCore-1.16
    - name: Clone ELT repository
      uses: actions/checkout@v2
      with:
        path: ELT-1.16
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          **/.gradle
          !**/.gradle/libs
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Gradle
    - uses: burrunan/gradle-cache-action@v1
      name: Cache .gradle
      with:
        job-id: elt
#     - name: Copy gradle.properties
#       run: cp ./ELT-1.16/.github/gradle.properties ./ELT-1.16/
    - name: Grant execute permission for gradlew
      run: chmod +x ./EltCore-1.16/gradlew && chmod +x ./ELT-1.16/gradlew
    - name: Build with Gradle
      run: cd ./ELT-1.16/ && ./gradlew build
    - name: Upload a ELT Build Artifact
      uses: actions/upload-artifact@v2.0.1
      with:
        name: ELT Artifact
        path: ./ELT-1.16/build/libs
    - name: Upload a ELT-Core Build Artifact
      uses: actions/upload-artifact@v2.0.1
      with:
        name: ELT-Core Artifact
        path: ./EltCore-1.16/build/libs
